name: Build and Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: write
      id-token: write

    env:
      NODE_OPTIONS: "--max-old-space-size=4096"  

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true  

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build:cdn

      - name: Netlify Actions
        uses: nwtgck/actions-netlify@v3.0.0
        with:
          publish-dir: ./dist
          deploy-message: "Deploy ${{ github.sha }}"
          production-branch: main
          production-deploy: true
          enable-commit-status: true
          fails-without-credentials: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
